name: flutter_application_trio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.14.0
  firebase_auth: ^4.8.1
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  percent_indicator: ^4.2.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.20.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon_app.png" # Ruta del archivo del ícono

flutter:
  uses-material-design: true


  assets:
  - lib/assets/images/